apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-instance
  namespace: monitoring
  labels:
    dashboards: grafana-instance
spec:
  config:
    log:
      mode: console
    security:
      admin_user: "admin"
      admin_password: "admin"
