apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: monitoring
spec:
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki.monitoring.svc.cluster.local:3100
  instanceSelector:
    matchLabels:
      dashboards: grafana-instance
